spring.application.name=MoneyMissint
spring.datasource.url=jdbc:postgresql://localhost:5432/moneymissint
spring.datasource.username=emiliorevueltasv
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
application.security.jwt.secret_key=${JWT_SECRET}